export const CONTACT_REQUEST = 'CONTACT_REQUEST'
export const CONTACT_RECIEVE = 'CONTACT_RECIEVE'
export const CONTACT_FAILURE = 'CONTACT_FAILURE'
export const RESET_CONTACT_STATE = 'RESET_CONTACT_STATE'
